// Static ISO-3166 country list used to populate the country dropdown.
// The canonical DataForSEO name and location_code are resolved lazily per country
// (see getCountryMeta in ./geo), so a name mismatch here never reaches the API.
export type Country = {iso: string; name: string};

export const COUNTRIES: Country[] = [
  {iso: "AF", name: "Afghanistan"},
  {iso: "AL", name: "Albania"},
  {iso: "DZ", name: "Algeria"},
  {iso: "AS", name: "American Samoa"},
  {iso: "AD", name: "Andorra"},
  {iso: "AO", name: "Angola"},
  {iso: "AI", name: "Anguilla"},
  {iso: "AG", name: "Antigua & Barbuda"},
  {iso: "AR", name: "Argentina"},
  {iso: "AM", name: "Armenia"},
  {iso: "AW", name: "Aruba"},
  {iso: "AU", name: "Australia"},
  {iso: "AT", name: "Austria"},
  {iso: "AZ", name: "Azerbaijan"},
  {iso: "BS", name: "Bahamas"},
  {iso: "BH", name: "Bahrain"},
  {iso: "BD", name: "Bangladesh"},
  {iso: "BB", name: "Barbados"},
  {iso: "BY", name: "Belarus"},
  {iso: "BE", name: "Belgium"},
  {iso: "BZ", name: "Belize"},
  {iso: "BJ", name: "Benin"},
  {iso: "BM", name: "Bermuda"},
  {iso: "BT", name: "Bhutan"},
  {iso: "BO", name: "Bolivia"},
  {iso: "BA", name: "Bosnia & Herzegovina"},
  {iso: "BW", name: "Botswana"},
  {iso: "BR", name: "Brazil"},
  {iso: "VG", name: "British Virgin Islands"},
  {iso: "BN", name: "Brunei"},
  {iso: "BG", name: "Bulgaria"},
  {iso: "BF", name: "Burkina Faso"},
  {iso: "BI", name: "Burundi"},
  {iso: "KH", name: "Cambodia"},
  {iso: "CM", name: "Cameroon"},
  {iso: "CA", name: "Canada"},
  {iso: "CV", name: "Cape Verde"},
  {iso: "KY", name: "Cayman Islands"},
  {iso: "CF", name: "Central African Republic"},
  {iso: "TD", name: "Chad"},
  {iso: "CL", name: "Chile"},
  {iso: "CN", name: "China"},
  {iso: "CO", name: "Colombia"},
  {iso: "KM", name: "Comoros"},
  {iso: "CG", name: "Congo - Brazzaville"},
  {iso: "CD", name: "Congo - Kinshasa"},
  {iso: "CR", name: "Costa Rica"},
  {iso: "CI", name: "Côte d’Ivoire"},
  {iso: "HR", name: "Croatia"},
  {iso: "CU", name: "Cuba"},
  {iso: "CW", name: "Curaçao"},
  {iso: "CY", name: "Cyprus"},
  {iso: "CZ", name: "Czechia"},
  {iso: "DK", name: "Denmark"},
  {iso: "DJ", name: "Djibouti"},
  {iso: "DM", name: "Dominica"},
  {iso: "DO", name: "Dominican Republic"},
  {iso: "EC", name: "Ecuador"},
  {iso: "EG", name: "Egypt"},
  {iso: "SV", name: "El Salvador"},
  {iso: "GQ", name: "Equatorial Guinea"},
  {iso: "ER", name: "Eritrea"},
  {iso: "EE", name: "Estonia"},
  {iso: "SZ", name: "Eswatini"},
  {iso: "ET", name: "Ethiopia"},
  {iso: "FJ", name: "Fiji"},
  {iso: "FI", name: "Finland"},
  {iso: "FR", name: "France"},
  {iso: "GA", name: "Gabon"},
  {iso: "GM", name: "Gambia"},
  {iso: "GE", name: "Georgia"},
  {iso: "DE", name: "Germany"},
  {iso: "GH", name: "Ghana"},
  {iso: "GI", name: "Gibraltar"},
  {iso: "GR", name: "Greece"},
  {iso: "GL", name: "Greenland"},
  {iso: "GD", name: "Grenada"},
  {iso: "GU", name: "Guam"},
  {iso: "GT", name: "Guatemala"},
  {iso: "GN", name: "Guinea"},
  {iso: "GW", name: "Guinea-Bissau"},
  {iso: "GY", name: "Guyana"},
  {iso: "HT", name: "Haiti"},
  {iso: "HN", name: "Honduras"},
  {iso: "HK", name: "Hong Kong SAR China"},
  {iso: "HU", name: "Hungary"},
  {iso: "IS", name: "Iceland"},
  {iso: "IN", name: "India"},
  {iso: "ID", name: "Indonesia"},
  {iso: "IQ", name: "Iraq"},
  {iso: "IE", name: "Ireland"},
  {iso: "IL", name: "Israel"},
  {iso: "IT", name: "Italy"},
  {iso: "JM", name: "Jamaica"},
  {iso: "JP", name: "Japan"},
  {iso: "JO", name: "Jordan"},
  {iso: "KZ", name: "Kazakhstan"},
  {iso: "KE", name: "Kenya"},
  {iso: "KI", name: "Kiribati"},
  {iso: "KW", name: "Kuwait"},
  {iso: "KG", name: "Kyrgyzstan"},
  {iso: "LA", name: "Laos"},
  {iso: "LV", name: "Latvia"},
  {iso: "LB", name: "Lebanon"},
  {iso: "LS", name: "Lesotho"},
  {iso: "LR", name: "Liberia"},
  {iso: "LY", name: "Libya"},
  {iso: "LI", name: "Liechtenstein"},
  {iso: "LT", name: "Lithuania"},
  {iso: "LU", name: "Luxembourg"},
  {iso: "MO", name: "Macao SAR China"},
  {iso: "MG", name: "Madagascar"},
  {iso: "MW", name: "Malawi"},
  {iso: "MY", name: "Malaysia"},
  {iso: "MV", name: "Maldives"},
  {iso: "ML", name: "Mali"},
  {iso: "MT", name: "Malta"},
  {iso: "MH", name: "Marshall Islands"},
  {iso: "MR", name: "Mauritania"},
  {iso: "MU", name: "Mauritius"},
  {iso: "MX", name: "Mexico"},
  {iso: "FM", name: "Micronesia"},
  {iso: "MD", name: "Moldova"},
  {iso: "MC", name: "Monaco"},
  {iso: "MN", name: "Mongolia"},
  {iso: "ME", name: "Montenegro"},
  {iso: "MA", name: "Morocco"},
  {iso: "MZ", name: "Mozambique"},
  {iso: "MM", name: "Myanmar (Burma)"},
  {iso: "NA", name: "Namibia"},
  {iso: "NR", name: "Nauru"},
  {iso: "NP", name: "Nepal"},
  {iso: "NL", name: "Netherlands"},
  {iso: "NZ", name: "New Zealand"},
  {iso: "NI", name: "Nicaragua"},
  {iso: "NE", name: "Niger"},
  {iso: "NG", name: "Nigeria"},
  {iso: "MK", name: "North Macedonia"},
  {iso: "NO", name: "Norway"},
  {iso: "OM", name: "Oman"},
  {iso: "PK", name: "Pakistan"},
  {iso: "PW", name: "Palau"},
  {iso: "PS", name: "Palestinian Territories"},
  {iso: "PA", name: "Panama"},
  {iso: "PG", name: "Papua New Guinea"},
  {iso: "PY", name: "Paraguay"},
  {iso: "PE", name: "Peru"},
  {iso: "PH", name: "Philippines"},
  {iso: "PL", name: "Poland"},
  {iso: "PT", name: "Portugal"},
  {iso: "PR", name: "Puerto Rico"},
  {iso: "QA", name: "Qatar"},
  {iso: "RO", name: "Romania"},
  {iso: "RU", name: "Russia"},
  {iso: "RW", name: "Rwanda"},
  {iso: "WS", name: "Samoa"},
  {iso: "SM", name: "San Marino"},
  {iso: "ST", name: "São Tomé & Príncipe"},
  {iso: "SA", name: "Saudi Arabia"},
  {iso: "SN", name: "Senegal"},
  {iso: "RS", name: "Serbia"},
  {iso: "SC", name: "Seychelles"},
  {iso: "SL", name: "Sierra Leone"},
  {iso: "SG", name: "Singapore"},
  {iso: "SK", name: "Slovakia"},
  {iso: "SI", name: "Slovenia"},
  {iso: "SB", name: "Solomon Islands"},
  {iso: "SO", name: "Somalia"},
  {iso: "ZA", name: "South Africa"},
  {iso: "KR", name: "South Korea"},
  {iso: "SS", name: "South Sudan"},
  {iso: "ES", name: "Spain"},
  {iso: "LK", name: "Sri Lanka"},
  {iso: "KN", name: "St. Kitts & Nevis"},
  {iso: "LC", name: "St. Lucia"},
  {iso: "VC", name: "St. Vincent & Grenadines"},
  {iso: "SD", name: "Sudan"},
  {iso: "SR", name: "Suriname"},
  {iso: "SE", name: "Sweden"},
  {iso: "CH", name: "Switzerland"},
  {iso: "SY", name: "Syria"},
  {iso: "TW", name: "Taiwan"},
  {iso: "TJ", name: "Tajikistan"},
  {iso: "TZ", name: "Tanzania"},
  {iso: "TH", name: "Thailand"},
  {iso: "TL", name: "Timor-Leste"},
  {iso: "TG", name: "Togo"},
  {iso: "TO", name: "Tonga"},
  {iso: "TT", name: "Trinidad & Tobago"},
  {iso: "TN", name: "Tunisia"},
  {iso: "TR", name: "Türkiye"},
  {iso: "TM", name: "Turkmenistan"},
  {iso: "UG", name: "Uganda"},
  {iso: "UA", name: "Ukraine"},
  {iso: "AE", name: "United Arab Emirates"},
  {iso: "GB", name: "United Kingdom"},
  {iso: "US", name: "United States"},
  {iso: "UY", name: "Uruguay"},
  {iso: "UZ", name: "Uzbekistan"},
  {iso: "VU", name: "Vanuatu"},
  {iso: "VE", name: "Venezuela"},
  {iso: "VN", name: "Vietnam"},
  {iso: "YE", name: "Yemen"},
  {iso: "ZM", name: "Zambia"},
  {iso: "ZW", name: "Zimbabwe"}
];
