// Server-side reader for the SEO meta tags generated by the n8n workflow,
// stored in Supabase table `seo_agent_runs`. Read-only.

export type Lang = 'en' | 'ru' | 'ar' | 'fr';

export type EventMeta = {
  event_id: string;
  event_url: string | null;
  status: string | null;
  published: boolean | null;
  finished_at: string | null;
  event_types: string[] | null;
  performers: string[] | null;
  generated_langs: string[] | null;
  h1: Record<Lang, string | null>;
  meta_title: Record<Lang, string | null>;
  meta_description: Record<Lang, string | null>;
};

type Row = Record<string, unknown>;

const SELECT = [
  'event_id', 'event_url', 'status', 'published', 'finished_at',
  'event_types', 'performers', 'generated_langs',
  'h1_en', 'meta_title_en', 'meta_desc_en',
  'h1_ru', 'meta_title_ru', 'meta_desc_ru',
  'h1_ar', 'meta_title_ar', 'meta_desc_ar',
  'h1_fr', 'meta_title_fr', 'meta_desc_fr'
].join(',');

function shape(r: Row): EventMeta {
  const s = (k: string) => (r[k] == null ? null : String(r[k]));
  return {
    event_id: String(r.event_id),
    event_url: s('event_url'),
    status: s('status'),
    published: r.published == null ? null : Boolean(r.published),
    finished_at: s('finished_at'),
    event_types: Array.isArray(r.event_types) ? (r.event_types as string[]) : null,
    performers: Array.isArray(r.performers) ? (r.performers as string[]) : null,
    generated_langs: Array.isArray(r.generated_langs) ? (r.generated_langs as string[]) : null,
    h1: {en: s('h1_en'), ru: s('h1_ru'), ar: s('h1_ar'), fr: s('h1_fr')},
    meta_title: {en: s('meta_title_en'), ru: s('meta_title_ru'), ar: s('meta_title_ar'), fr: s('meta_title_fr')},
    meta_description: {en: s('meta_desc_en'), ru: s('meta_desc_ru'), ar: s('meta_desc_ar'), fr: s('meta_desc_fr')}
  };
}

export async function getEventMeta(limit = 100): Promise<EventMeta[]> {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    throw new Error('SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY is not set');
  }

  const endpoint =
    `${url}/rest/v1/seo_agent_runs` +
    `?select=${encodeURIComponent(SELECT)}` +
    `&event_id=not.is.null` +
    `&order=finished_at.desc` +
    `&limit=300`;

  const res = await fetch(endpoint, {
    headers: {apikey: key, Authorization: `Bearer ${key}`},
    cache: 'no-store'
  });
  if (!res.ok) {
    throw new Error(`Supabase read failed: ${res.status}`);
  }
  const rows = (await res.json()) as Row[];

  // Keep only the latest run per event (rows already ordered desc by finished_at)
  const seen = new Set<string>();
  const out: EventMeta[] = [];
  for (const r of rows) {
    const id = String(r.event_id);
    if (seen.has(id)) continue;
    seen.add(id);
    out.push(shape(r));
    if (out.length >= limit) break;
  }
  return out;
}
